import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ThemeProvider } from 'styled-components'
import { defaultTheme } from '../style/theme'
import StyledComponentsRegistry from '@/lib/registry'
import GlobalStyle from '../style'
import { Container, Header } from '@/atomic-components'

const openSans = Open_Sans({ subsets: ['latin'], weight: ['400', '600', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={openSans.className}>
        <StyledComponentsRegistry>
          <Container>
            <Header />
          </Container>
          <Container>{children}</Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
